siteTitle="Smooch Docs"

[sections.docs]
subsections = [
    'home',
    'programmable-messaging',
    'users',
    'managed-accounts',
    'smooch-connect',
    'channels',
    'built-in-integrations',
    'references'
]

[sections.api]
subsections = [
    'rest'
]

[subsections.home]
name = "Home"
pages = [
    "/docs/",
    "/docs/api-quickstart/",
    "/docs/business-quickstart/"
]

[subsections.programmable-messaging]
name = "Programmable Messaging"
pages = [
    "/docs/authenticating-to-smooch-api/",
    "/docs/sending-and-receiving-messages/"
]

[subsections.users]
name = "Users"
pages = [
    "/docs/creating-users/",
    "/docs/authenticating-users/",
    "/docs/managing-user-information/",
    "/docs/linking-users-to-sms/"
]

[subsections.managed-accounts]
name = "Managed Accounts"
pages = [
    "/docs/creating-and-managing-apps/",
    "/docs/configuring-messaging-channels/",
]

[subsections.smooch-connect]
name = "Smooch Connect"
pages = [
    "/docs/oauth/",
    "/docs/becoming-an-integration-partner/",
]

[subsections.channels]
name = "Channels"
pages = [
    "/docs/native-sdks/",
    "/docs/ott-messenger/",
    "/docs/email/",
    "/docs/channel-capabilities/"
]

[subsections.built-in-integrations]
name = "Built-in Integrations"
pages = [
    "/docs/configuring-business-systems/",
    "/docs/stripe-payments/",
    "/docs/automated-messages/",
    "/docs/office-hours/"
]

[subsections.references]
name = "References"
pages = [
    "API Reference__https://docs.smooch.io/rest/",
    "/docs/error-messages/",
    "/changelog/",
    "/docs/webhooks-specs/",
    "/docs/security/",
    "/docs/technical-info/",
    "/docs/faq/",
    "/docs/sending-images-and-buttons-shorthand/",
]

[subsections.rest]
name = "REST"
pages = [
    "/api/",
    "/api/connect/",
    "/api/inside/"
]
